name: Proximity
version: 1.0.3
author: Vhbob
main: io.github.vhorvath2010.proximity.Proximity
commands:
  Proximity:
    description: The base command for Proximity
permissions:
  proximity.reload:
    description: Allows users to reload Proximity
    default: op
  proximity.bypass.listen:
    description: Allows users to bypass the proximity requirements when listening
    default: op
  proximity.bypass.speak:
    description: Allows users to bypass the proximity requirements when speaking
    default: op
  proximity.bypass.*:
    children:
      proximity.bypass.listen: true
      proximity.bypass.speak: true
  proximity.*:
    children:
      proximity.bypass.*: true
      proximity.reload: true